### PR TITLE
Add prepare for validation to merge the route request to validation b…

### PR DESCRIPTION
**Pull request by DevYSM**
I added a new method that helps the developers to merge a route parameter for the validation request like the Laravel custom form request.

### CODE REVIEW

**Comment by ssi-anik** [comment]
Thanks for the PR. tagged with `v4.5`.

**Comment by DevYSM** [comment]
You're welcome, Also you should add the method name in the Readme file.
Thanks for your package <3

**Comment by DevYSM** [comment]
The developers can use the method in this way.

>     protected function prepareForValidation() {
>       $this->mergeIfMissing(['id' => $this->route('id')]);  }

**Comment by ssi-anik** [comment]
> The developers can use the method in this way.
> 
> > ```
> > protected function prepareForValidation() {
> >   $this->mergeIfMissing(['id' => $this->route('id')]);  }
> > ```

May be you can just add to readme as a point?

**Comment by DevYSM** [comment]
Yes that's I'm meaning👌👌

**Pull request merged**
